### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by ctwhome** [antfu/vitesse-nuxt-bridge#4]
Thanks for this project, I was very eager to try it with all your latest developments, UnoCSS already in this project? omg!

when running `yarn dev` or `ni dev` it can't find nuxi

![](https://user-images.githubusercontent.com/4195550/139423455-7c0f5091-db8d-47a9-98ef-548436ff97cf.png)

**Comment by antfu** [comment]
I am running it without problem, have you installed the deps yet? (we are using pnpm here btw)

**Comment by ctwhome** [comment]
Running it out of the box after cloning the repo I get this:
![image](https://user-images.githubusercontent.com/4195550/139523278-36ef0a7f-a958-4029-b6b9-88a705660484.png)

![image](https://user-images.githubusercontent.com/4195550/139523312-2d9c5ebd-de38-4b83-b872-bfb481dfff81.png)

![image](https://user-images.githubusercontent.com/4195550/139523314-36b90423-e31c-43ae-8a1c-0d71ce70a9b6.png)

**Comment by ctwhome** [comment]
it runs after the latest changes in https://github.com/antfu/vitesse-nuxt/commit/af33ccb97b877353fe7917d8dcf16961f9acf1d6 thank you for the effort
