### ISSUE TITLE
HRM Doesn't work with Styles

### ISSUE THREAD

**Issue by ctwhome** [antfu/vitesse-nuxt-bridge#6]
This is a different issue that affects Tailwindcss and WindiCss when using Vite. Changing the styles in the template doesn't update the browser. You are probably aware of the problem, but Is this something that you could take a look? thanks!

more details in nuxt/vite#164

![](https://user-images.githubusercontent.com/4195550/139633989-c190cf60-b919-4dde-896e-20afdbcb52d5.png)

**Comment by maninak** [comment]
I think it's fixed since https://github.com/antfu/vitesse-nuxt-bridge/commit/0f60b6c7a5cc92b05894f88be80e4ce595138ac1, can you please give it another try with the latest `main` branch?

**Comment by ctwhome** [comment]
hi, thanks for the comment. I tried and it works
