### ISSUE TITLE
The requested module 'vue-demi' does not provide an export named 'computed'

### ISSUE THREAD

**Issue by sumitkolhe** [antfu/vitesse-nuxt-bridge#8]
Getting `The requested module 'vue-demi' does not provide an export named 'computed'` error when running the starter. 

Steps followed - 

`pnpm i`
`pnpm run dev`

**Comment by maninak** [comment]
I just tried with commit `df6c1f45963e5adf21e4645a304e1ef70b993392` (probably the one you also used) and it worked on my machine without any issues.

Running node v16.13.0 on Linux.
